// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hospitals/nearest": {
            "post": {
                "description": "Returns a list of nearest hospitals to the provided location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hospitals"
                ],
                "summary": "Get Nearest Hospitals",
                "parameters": [
                    {
                        "description": "Nearest hospitals request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NearestHospitalsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Location"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/api/v1/location/nearest": {
            "post": {
                "description": "Retrieves users nearest to given coordinates within a radius.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "location"
                ],
                "summary": "Get nearest users",
                "parameters": [
                    {
                        "description": "Nearest users request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.NearestUsersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.NearestUsersResponse"
                            }
                        }
                    },
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "Authenticate user and return user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "authenticated user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "401": {
                        "description": "invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics": {
            "get": {
                "description": "Retrieve health metrics for a given user by query parameter user_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get health metrics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "list of health metrics",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid user_id or missing parameter",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "failed to get health metrics",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "Create health metrics for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Create health metrics",
                "parameters": [
                    {
                        "description": "Health metrics payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.HealthMetricsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "status message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "failed to create health metrics",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/api/v1/recommendation": {
            "get": {
                "description": "Returns a recommendation string",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Recommendation"
                ],
                "summary": "Get Recommendation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.RecommendationResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created user id",
                        "schema": {
                            "$ref": "#/definitions/entity.CreatedUserResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    },
                    "500": {
                        "description": "failed to register user",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the live status of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check (Live)",
                "responses": {
                    "200": {
                        "description": "health",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.CreatedUserResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "entity.ErrorMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.HealthMetric": {
            "type": "object",
            "properties": {
                "metric_type": {
                    "type": "string"
                },
                "metric_value": {
                    "type": "string"
                }
            }
        },
        "entity.HealthMetricsRequest": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.HealthMetric"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "entity.Location": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 55.755825
                },
                "longitude": {
                    "type": "number",
                    "example": 37.617396
                }
            }
        },
        "entity.NearestHospitalsRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 55.755825
                },
                "longitude": {
                    "type": "number",
                    "example": 37.617396
                },
                "radius": {
                    "description": "in meters",
                    "type": "integer",
                    "example": 5000
                }
            }
        },
        "entity.NearestUsersRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 55.755825
                },
                "longitude": {
                    "type": "number",
                    "example": 37.617396
                },
                "radius": {
                    "description": "in meters",
                    "type": "integer",
                    "example": 5000
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "entity.NearestUsersResponse": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/entity.Location"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "entity.RecommendationResponse": {
            "type": "object",
            "properties": {
                "recommendation": {
                    "type": "string"
                }
            }
        },
        "entity.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "entity.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Dockify Backend API",
	Description:      "API for Dockify backend.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
